global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 1h
  routes:
    - receiver: 'gmail-notifications'  

receivers:
  - name: 'gmail-notifications'
    email_configs:
      - to: '${ALERTMANAGER_AUTH_RECEIVER}, ${ALERTMANAGER_AUTH_USERNAME}' 
        from: ${ALERTMANAGER_AUTH_USERNAME}
        smarthost: smtp.gmail.com:587
        auth_username: ${ALERTMANAGER_AUTH_USERNAME}
        auth_identity: ${ALERTMANAGER_AUTH_USERNAME}
        auth_password: ${ALERTMANAGER_AUTH_PASSWORD}
        send_resolved: true
